import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Switches the Android launcher icon between the light and dark variants.
///
/// Native side: `MainActivity.kt` (generated by tool/configure_android.sh)
/// flips two manifest <activity-alias> entries. Android only; a no-op elsewhere.
class AppIconService {
  AppIconService._();

  static const MethodChannel _channel = MethodChannel('noted/app_icon');
  static bool? _last; // last state we asked for, so we only call native on a change

  /// [dark] is the resolved app theme. When [enabled] is false the light icon
  /// (the default) is restored.
  static Future<void> sync({required bool dark, required bool enabled}) async {
    if (kIsWeb || defaultTargetPlatform != TargetPlatform.android) return;
    final wantDark = enabled && dark;
    if (_last == wantDark) return;
    _last = wantDark;
    try {
      await _channel.invokeMethod<void>('setIcon', {'dark': wantDark});
    } on PlatformException {
      // Never let a cosmetic feature affect the app.
    } on MissingPluginException {
      // Not running with the Android side (e.g. tests): ignore.
    }
  }
}
